# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

stages:
    - build
    - test

.parallel-tests:
    parallel:
        matrix:
            - TEST:
                - services/core/ActuatorAgent/tests
                - services/core/DataMover/tests/
                - services/core/DNP3OutstationAgent/tests
                - services/core/ForwardHistorian/tests

# build 22.04:
#     stage: build
#     tags:
#         - ubuntu2204

#     before_script:
#         #- killall -9 volttron beam.smp python
#         - rm -rf dist ~/.volttron ~/.volttron_instances
#         - rm -rf /tmp/tmp*
#         - rm -rf ~/rabbitmq_server

#     script:
#         - python3 bootstrap.py --all
#         - source env/bin/activate
#         - python3 bootstrap.py --rabbitmq
#         - echo "BUILD_DIR_22_04=`pwd`" >> build.env
#         - echo "$BUILD_DIR_22_04"
#         - echo `pwd`

#     artifacts:
#         reports:
#             dotenv: build.env

build 20.04:
    stage: build
    tags:
        - ubuntu2004

    before_script:
        #- killall -9 volttron beam.smp python
        - rm -rf dist ~/.volttron ~/.volttron_instances
        - rm -rf /tmp/tmp*
        - rm -rf ~/rabbitmq_server

    script:
        - python3 bootstrap.py --all
        - source env/bin/activate
        - python3 bootstrap.py --rabbitmq
        - echo "BUILD_DIR_20_04=`pwd`" >> build.env
        - echo "$BUILD_DIR_20_04"
        - echo `pwd`

    artifacts:
        reports:
            dotenv: build.env


# test 22.04:
#     stage: test
#     needs: [build 22.04]
#     variables:
#             GIT_CHECKOUT: "false"
#     tags:
#         - ubuntu2204
#     extends: .parallel-tests
#     script:
#             - cd $BUILD_DIR_22_04
#             - echo `pwd`
#             - source env/bin/activate
#             - pytest $TEST


test 20.04:
    stage: test
    needs: [build 20.04]
    variables:
            GIT_CHECKOUT: "false"
    tags:
        - ubuntu2004
    extends: .parallel-tests
    script:
            - cd $BUILD_DIR_20_04
            - echo `pwd`
            - source env/bin/activate
            - pytest $TEST


